#!/usr/bin/env bash
set -e
set -u
set -o pipefail

for file in $(find . -type f -name '*.sql'); do
    echo "Formatting $file"
    pg_format \
        --inplace "$file" \
        --config ./pg_format.conf
done
